package com.rabbit.samples.employeeservice.web.controllers;

import com.rabbit.samples.employeeservice.services.EmployeeService;
import com.rabbit.samples.employeeservice.web.dtos.EmployeeDto;
import com.rabbit.samples.employeeservice.web.mappers.EmployeeMapper;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.stream.Collectors;


@Slf4j
@FieldDefaults(level = AccessLevel.PRIVATE)
@Getter(value = AccessLevel.PROTECTED)
@RestController("employeeRestController")
@RequestMapping("/employees")
public class EmployeeRestController {

	@Autowired
	@Qualifier("employeeService")
	EmployeeService employeeService;

	// PLASE NOTE: no specific qualifier because generated by MapStruct
	@Autowired
	EmployeeMapper employeeMapper;

	@GetMapping
	public List<EmployeeDto> getAll() {

		log.debug("get all employees...");

		return getEmployeeService().getAll()
				.stream()
				.map(getEmployeeMapper()::mapEntityToDto)
				.collect(Collectors.toList());
	}

	@GetMapping("/id")
	public EmployeeDto getById(
			@RequestParam final Long id) {

		log.debug("get employee by id {}...", id);

		return getEmployeeMapper().mapEntityToDto(
				getEmployeeService().getById(id)
		);
	}

	@GetMapping("/name")
	public EmployeeDto getByName(
			@RequestParam final String name) {

		log.debug("get employee by name {}...", name);

		return getEmployeeMapper().mapEntityToDto(
				getEmployeeService().getByName(name)
		);
	}

	@PostMapping
	@ResponseStatus(HttpStatus.CREATED)
	public EmployeeDto create(
			@RequestBody final EmployeeDto newEmployeeDto) {

		log.debug("post new employee {}...", newEmployeeDto);

		return getEmployeeMapper().mapEntityToDto(
				getEmployeeService().save(
						getEmployeeMapper().mapDtoToEntity(newEmployeeDto)
				)
		);
	}

}
